version: "3.5"

services:
  websocket:
    build:
      context: .
      args:
         - NODE_ENV=development
    command: ['make', 'dev_server']
    ports:
      - 3000:3000
    env_file:
      - ./.env
    volumes:
      - ./:/opt
    restart: always

  unit-tests:
    build:
      context: .
      args:
        - NODE_ENV=test
    command: ['make', 'test']
    env_file:
      - ./.env
    environment:
      NODE_ENV: test
      DB_NAME: turbulent_test
    ports:
      - 9001:9229
    volumes:
      - ./:/opt:delegated
    restart: always
