version: "3.5"

volumes:
  postgres-data:

services:
  websocket:
    build:
      context: .
      args:
         - NODE_ENV=development
    command: ['make', 'dev_server']
    ports:
      - 3000:3000
    env_file:
      - ./.env
    volumes:
      - ./:/opt
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: turbulent_development
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  unit-tests:
    build:
      context: .
      args:
        - NODE_ENV=test
    command: ['make', 'test']
    env_file:
      - ./.env
    environment:
      NODE_ENV: test
      DB_NAME: turbulent_test
    ports:
      - 9001:9229
    volumes:
      - ./:/opt:delegated
    restart: always
    depends_on:
      - postgres
