version: "3.5"

services:
  websocket:
    build:
      context: .
      args:
         - NODE_ENV=development
    command: ['make', 'dev_server']
    ports:
      - 3000:3000
    volumes:
      - ./:/opt
    restart: always
